version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    ports:
     - "4000:27017"
    restart: always

  video-storage:
    image: video-storage-prod
    build: 
      context: ./video-storage
      dockerfile: Dockerfile-prod
    container_name: video-storage-prod
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} #replace with this varible with your aws access key
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} #replace with this varible with you aws secret access key
    restart: "no"

  video-streaming:
    image: video-streaming-prod
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-prod
    container_name: video-streaming-prod
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"

  history:
    image: history-prod
    build: 
      context: ./history
      dockerfile: Dockerfile-prod
    container_name: history-prod
    ports:
      - "4003:80"
    environment:
      - PORT=80
    restart: "no"
